[toolchain]
channel = "stable"
targets = ["wasm32-unknown-unknown"]
components = ["rust-src"]

# Check profiles for more information:
# https://rust-lang.github.io/rustup/concepts/profiles.html
profile = "default"
