[toolchain]
channel = "stable"
targets = []
components = ["rust-src", "llvm-tools-preview"]

# Check profiles for more information:
# https://rust-lang.github.io/rustup/concepts/profiles.html
profile = "default"
