[package]
name = "airdrop"
version = "0.1.0"
edition.workspace = true

[features]
default = []
tokio-console = ["dep:console-subscriber"]

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
console-subscriber = { workspace = true, optional = true }
dotenvy = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
non-membership-proofs = { workspace = true }
orchard = { workspace = true }
rs_merkle = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
sapling = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["hex"] }
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "macros",
  "io-util",
  "tracing",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
zcash_protocol = { workspace = true }

[lints]
workspace = true
