name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag: v6.0.1
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # branch=master
        with:
          toolchain: stable
      - name: Install cargo-bininstall
        uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # tag: v2.65.1
        with:
          tool: cargo-binstall
      - name: Install mdbook and plugins
        run: |
          cargo binstall -y 'mdbook@0.4.52' || cargo install --locked mdbook --version 0.4.52
          cargo binstall -y mdbook-katex mdbook-admonish || cargo install --locked mdbook-katex mdbook-admonish
      - uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # tag: v4
      - name: Build
        run: mdbook build docs
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # tag: v3
        with:
          path: docs/book
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # tag: v4
